login/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from login.views import login_view, register, edit_user , show_profile 

app_name = 'login'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register, name='register'),
    path('logout/', LogoutView.as_view(next_page="landing_news:landing"), name='logout'),
    path('profile/', show_profile, name='profile'),
    path('edit_profile/', edit_user, name='edit_profile')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_news.urls')),
    path('games/', include('tables.urls')),
    path('login/', include('login.urls'))


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from django import forms


class User_edit_form(UserChangeForm):

    password= forms.CharField(
        help_text="",
        widget= forms.HiddenInput(), required=False
    )

    password1=forms.CharField(label="Contraseña",  widget=forms.PasswordInput)
    password2=forms.CharField(label="Repetir contraseña",  widget=forms.PasswordInput)

    class Meta:
        model = User
        fields= ["first_name",  "last_name", "email"]

    def clean_password2(self):
        password1=self.cleaned_data["password1"]
        password2=self.cleaned_data["password2"]
        
        if password1 != password2:
            raise forms.ValidationError ("Las contraseñas no coinciden")
        return password2

    def __init__(self, *args, **kwargs):
        super(User_edit_form, self).__init__(*args, **kwargs)
        #self.fields['username'].label = 'Nombre de Usuario'
        self.fields['first_name'].label = 'Nombre'
        self.fields['last_name'].label = 'Apellido'
        self.fields['email'].label = 'Correo Electrónico'  
    
    
    
    


 

login/views.py
from django.shortcuts import render , redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm 
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from login.forms import User_edit_form 

# Create your views here.

def login_view(req):

    if req.method == 'POST':

        myform = AuthenticationForm(req, data=req.POST)

        if myform.is_valid():

            data = myform.cleaned_data

            user = data["username"]
            psw = data["password"]

            user = authenticate(username=user, password=psw)

            if user:
                login(req, user)
                return redirect('landing_news:landing')
            
            else:
                myform = AuthenticationForm()

                return render(req, "login/login.html", {"message": "Datos inválidos intente nuevamente", "myform":myform})
    
        else:
            myform = AuthenticationForm()

            return render(req, "login/login.html", {"message": "Datos inválidos intente nuevamente","myform":myform })
    
    else:

        myform = AuthenticationForm()

        return render(req, "login/login.html", {"myform": myform})
  

def register(req):

    if req.method == 'POST':

        myform = UserCreationForm(req.POST)

        if myform.is_valid():

            data = myform.cleaned_data

            user= data["username"]
            myform.save()
            
            messages.success(req, f'Usuario {user} creado con exito ')
            return redirect('login:login') 
        
        else:
            myform = UserCreationForm()
            return render(req, "login/register.html", {"message": "Datos inválidos" , "myform": myform})
    
    else:

        myform = UserCreationForm()

        return render(req, "login/register.html", {"myform": myform})
    

def show_profile(req):
    return render (req,"login/profile.html")
  
@login_required()
def edit_user(req):

    user = req.user

    if req.method == 'POST':

        myform = User_edit_form(req.POST, instance=req.user)

        if myform.is_valid():

            data = myform.cleaned_data

            user.first_name = data["first_name"]
            user.last_name = data["last_name"]
            user.email = data["email"]
            user.set_password(data["password1"])

            user.save()

            return render(req, "login/profile.html", {"message": "Datos actualizado con éxito"})
            
        else:

            return render(req, "login/edit_user.html", {"myform": myform})
    
    else:

        myform = User_edit_form(instance=req.user)

        return render(req, "login/edit_user.html", {"myform": myform})
    

    

login/templates/login/edit_user.html
{% extends 'landing_news/father.html' %}
{% load static %}

{% block title %}
    Editar usuario
{% endblock title %}



{% block body %}

   

    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <h1>Editar usuario</h1>

                <form action="{% url 'login:edit_profile' %}" method="post">{% csrf_token %}

                    {{myform.as_p}}
                  
                    <button type="submit"> Actualizar </button>
                  
                  </form>

                <a   href="{% url 'login:profile'%}">
                    <button type="button">Volver</button>
                </a>
                
            </div>
        </div>
    </div>

{% endblock body %}

login/templates/login/login.html
{% extends 'landing_news/father.html' %}
{% load static %}

{% block title %}
    Login
{% endblock title %}



{% block body %}

   

    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <h1>Iniciar sesion</h1>
                <h3>{{message}} </h3>
                {% if messages %}
                   
                {% for message in messages %}
                <h3> {{ message }} </h3>
                {% endfor %}
                
                {% endif %}

                <form action = "{% url 'login:login' %}" method= "post"> {% csrf_token %}
                    {{myform.as_p}}

                    <button type= "submit"> Ingresar </button>

                </form>

                <a   href="{% url 'landing_news:landing'%}">
                    <button type="button">Volver</button>
                </a>
                
            </div>
        </div>
    </div>

{% endblock body %}

login/templates/login/profile.html
{% extends 'landing_news/father.html' %}
{% load static %}

{% block title %}
    Mi perfil
{% endblock title %}



{% block body %}

   

    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <h1>Mi perfil</h1>
                {{message}}
                <ul>
                    <li>Usuario: {{request.user.username}} </li>
                    <li>Nombre {{request.user.first_name}} {{request.user.last_name}} </li>
                    <li>Email: {{request.user.email}} </li>
                </ul>
                
                <a   href="{% url 'login:edit_profile'%}">
                    <button type="button">Editar perfil</button>
                </a>

                <a   href="{% url 'landing_news:landing'%}">
                    <button type="button">Volver</button>
                </a>
                
            </div>
        </div>
    </div>

{% endblock body %}

login/templates/login/register.html
{% extends 'landing_news/father.html' %}
{% load static %}

{% block title %}
    Registro
{% endblock title %}



{% block body %}

  

    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <h1>Complete el formulario para registrarse</h1>
                <h3>{{message}} </h3>

                <form action = "{% url 'login:register' %}" method= "post"> {% csrf_token %}
                    {{myform.as_p}}

                    <button type= "submit"> Registrarse </button>

                </form>

                <a   href="{% url 'landing_news:landing'%}">
                    <button type="button">Volver</button>
                </a>
                
            </div>
        </div>
    </div>

{% endblock body %}