login/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from login.views import login_view, register, edit_user , show_profile 

app_name = 'login'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register, name='register'),
    path('logout/', LogoutView.as_view(next_page="landing_news:landing"), name='logout'),
    path('profile/', show_profile, name='profile'),
    path('edit_profile/', edit_user, name='edit_profile')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_news.urls')),
    path('games/', include('tables.urls')),
    path('login/', include('login.urls'))


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tables/urls.py
from django.urls import path
from tables.views import (
Player_list , Player_detail, Player_create, Player_update , Player_delete,
Tables_list , Table_detail , Table_create , Table_update , Table_delete
)

app_name = 'tables'

urlpatterns = [
    path('players/', Player_list.as_view(), name='players_list'),
    path('player/detail/<pk>', Player_detail.as_view(), name='player_detail'),
    path('player/create/', Player_create.as_view(), name='player_create'),
    path('player/update/<pk>', Player_update.as_view(), name='player_update'),
    path('player/delete/<pk>', Player_delete.as_view(), name='player_delete'),
]


urlpatterns  += [
    path('tables/', Tables_list.as_view(), name='tables_list'),
    path('table/detail/<pk>', Table_detail.as_view(), name='table_detail'),
    path('table/create/', Table_create.as_view(), name='table_create'),
    path('table/update/<pk>', Table_update.as_view(), name='table_update'),
    path('table/delete/<pk>', Table_delete.as_view(), name='table_delete'),
]

tables/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Game_table(models.Model):
    name = models.CharField(max_length=20, verbose_name="Nombre de la mesa:")
    game = models.CharField(max_length=20, verbose_name="Juego:")
    description = models.TextField(verbose_name="Descripcion")
    date=models.DateTimeField(verbose_name="Fecha")
    players = models.ManyToManyField('Player', related_name='player', blank=True)
    max_players = models.PositiveIntegerField(verbose_name="Cantidad de Jugadores")
    

    def __str__(self):
        return self.name

    def add_player(self, player):
        self.players.add(player)

    def free_places(self):
       cant= self.max_players - self.players.count()
       return cant
    
    class Meta:
        verbose_name = 'Mesa de juego'
        verbose_name_plural = 'Mesas de juego'
    


class Player(models.Model):

    name = models.CharField(max_length=30, verbose_name= "Nombre")
    lastname = models.CharField(max_length=30, verbose_name= "Apellido")
    email = models.EmailField()
    age= models.IntegerField(verbose_name="Edad")
    favorite_game = models.CharField(max_length=30, verbose_name="Juego favorito")
    player_picture = models.ImageField(upload_to='player_picture',null=True, blank=True, verbose_name="Imagen")
    #user_id = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} {self.lastname}"
    
    class Meta:
        verbose_name = 'Jugador'
        verbose_name_plural = 'Jugadores'

tables/forms.py
from django import forms
from tables.models import Game_table
from datetime import datetime


class Table_form(forms.ModelForm):

    class Meta:
        model = Game_table
        fields = ["name","game","description","date","max_players"]
        widgets = {
            'date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }


class Edit_table_form(forms.ModelForm):

    class Meta:
        model = Game_table
        fields = ["name","game","description","date"]
        widgets = {
            'date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }


class Player_create_form(forms.Form):

    name = forms.CharField(label= "Nombre")
    lastname = forms.CharField(label= "Apellido")
    email = forms.EmailField()
    age= forms.IntegerField(label="Edad")
    favorite_game = forms.CharField(label="Juego favorito")
    player_picture = forms.ImageField(required=False,label="Imagen")
  

tables/views.py
from tables.models import Player, Game_table
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView
from django.urls import reverse_lazy
from django.db.models import Q
from tables.forms import Table_form , Edit_table_form , Player_create_form
from django.contrib.auth.mixins import LoginRequiredMixin
from tables.mixins import  Login_staff
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth.models import User


#from django.contrib.admin.views.decorators import staff_member_required
# Create your views here.


class Player_list(Login_staff,ListView):
    model = Player
    template_name = 'tables/players_list.html'
    context_object_name = 'players'
    ordering = ['-name']

    def get_queryset(self):
        query = self.request.GET.get('q')
        queryset= Player.objects.all()
        if query:
            queryset= Player.objects.filter(
                Q(name__icontains=query) |
                Q(lastname__icontains=query)|
                Q(age__icontains=query)
                )
        return queryset.order_by('name')
    
class Player_detail(Login_staff,DetailView):
    model = Player
    context_object_name = 'player'


class Player_create(LoginRequiredMixin,CreateView):
    model = Player
    template_name = 'tables/player_create.html'
    fields = ('__all__')
    success_url =  reverse_lazy("tables:players_list")

# def Player_create(req):

#     if req.method =="POST":

#         new_player_form = Player_create_form(req.POST, req.FILES)
#         new_user_form = UserCreationForm(req.POST)


#         if new_player_form.is_valid() and new_user_form.is_valid():

#             data= new_player_form.cleaned_data
#             user_data = new_user_form.cleaned_data

#             user= User(username=user_data["username"])
#             user.set_password(user_data["password1"])
#             user.save()

#             new_player = Player(
#             name = data['name'],
#             lastname = data['lastname'],
#             email = data['email'],
#             age=data['age'],
#             favorite_game=data['favorite_game'],
#             player_picture=data['player_picture'],
#             user_id=user)
#             new_player.save()

#             return render(req, "tables/player_create.html"  , {"message":"Jugador  creado con exito"})
#         else:
#             return render(req, "tables/player_create.html"  , {"message":"Datos invalidos"})
    
#     else: 
#         myform= Player_create_form()
#         userform= UserCreationForm()

#         return render(req, "tables/player_create.html"  , {"myform":myform,"userform":userform})



class Player_update(LoginRequiredMixin,UpdateView):
    model = Player
    template_name = 'tables/player_update.html'
    fields = ('__all__')
    success_url =  reverse_lazy("tables:players_list")
    context_object_name = 'player'

class Player_delete(Login_staff,DeleteView):
    model = Player
    template_name = 'tables/player_delete.html'
    context_object_name = 'player'
    success_url =  reverse_lazy("tables:players_list")



# def Player_delete(req,pk,name):

#     if req.method =="POST":
#         player= Player.objects.get(id=pk)
#         user = player.user_id
#         user.delete()
#         return redirect("tables:players_list")
    
#     else:

#         return render(req, 'tables/player_delete.html', {'pk': pk, 'name':name})
    
        
   


class Tables_list(LoginRequiredMixin,ListView):
    model = Game_table
    template_name = 'tables/tables_list.html'
    context_object_name = 'tables'
    ordering = ['date']

    def get_queryset(self):
        query = self.request.GET.get('q')
        queryset= Game_table.objects.all()
        if query:
            queryset= Game_table.objects.filter(
                Q(name__icontains=query) |
                Q(game__icontains=query) 
                )
        return queryset.order_by('name')
    
class Table_detail(LoginRequiredMixin,DetailView):
    model = Game_table
    template_name = 'tables/table_detail.html'
    context_object_name = 'table'


class Table_create(LoginRequiredMixin,CreateView):
    model = Game_table
    form_class = Table_form
    template_name = 'tables/table_create.html'
    success_url =  reverse_lazy("tables:tables_list")



class Table_update(LoginRequiredMixin,UpdateView):
    model = Game_table
    template_name = 'tables/table_update.html'
    form_class = Edit_table_form
    success_url =  reverse_lazy("tables:tables_list")
    context_object_name = 'table'

class Table_delete(LoginRequiredMixin,DeleteView):
    model = Game_table
    template_name = 'tables/table_delete.html'
    context_object_name = 'table'
    success_url =  reverse_lazy("tables:tables_list")

tables/templates/tables/player_create.html
{% extends 'landing_news/father.html' %}
{% load static %}

{% block title %}
    Crea Jugador
{% endblock title %}



{% block body %}

    

    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <h1>Crear Jugador</h1>
                <h3>{{message}}</h3>
                

                <form action = "{% url 'tables:player_create' %}" method= "post" enctype="multipart/form-data"> {% csrf_token %}

                    {{form.as_p}}

                    <button type= "submit"> Crear </button>

                </form>

                <a   href="{% url 'tables:players_list'%}">
                    <button type="button">Volver</button>
                </a>
                
            </div>
        </div>
    </div>

{% endblock body %}

tables/templates/tables/player_delete.html
{% extends 'landing_news/father.html' %}
{% load static %}

{% block title %}
    Eliminar Jugador
{% endblock title %}



{% block body %}

    <h1>Eliminar Jugador </h1>

    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">

                <form action = "{% url 'tables:player_delete' player.id %}" method= "post" > {% csrf_token %}
                    <p> Esta seguro que desea eliminar a {{player.name}} {{player.lastname}} </p>

                    <button type = "submit"> Confirmar </button>
                    <button ><a href= "{% url 'tables:players_list'%}"> Cancelar </a></button>

                </form>


                
            </div>
        </div>
    </div>

{% endblock body %}

tables/templates/tables/player_detail.html
{% extends 'landing_news/father.html' %}
{% load static %}

{% block title %}
    Jugador
{% endblock title %}



{% block body %}

    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">

                <h1>{{player.name}} {{player.lastname}}</h1>

                <ul>
                    <li>Edad: {{player.age}}</li>
                    <li>Email: {{player.email}}</li>
                    <li>Juego favorito: {{player.favorite_game}}</li>
                </ul>

                {% if player.player_picture %}
                <img src="{{ player.player_picture.url }}" alt="Foto de {{ player.name }}" width="" height="">
                {% endif %}
                
                <a   href="{% url 'tables:players_list'%}">
                    <button type="button">Volver</button>
                </a>

            </div>
        </div>
    </div>
{% endblock body %}

tables/templates/tables/player_update.html
{% extends 'landing_news/father.html' %}
{% load static %}

{% block title %}
    Editar Jugador
{% endblock title %}



{% block body %}

    <h1>Editar Jugador </h1>

    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">

                <form action = "{% url 'tables:player_update' player.id %}" method= "post" enctype="multipart/form-data"> {% csrf_token %}
                    {{form.as_p}}

                    <button type= "submit"> Guardar </button>

                </form>

                <a   href="{% url 'tables:players_list'%}">
                    <button type="button">Volver</button>
                </a>
                
            </div>
        </div>
    </div>

{% endblock body %}

tables/templates/tables/players_list.html
{% extends 'landing_news/father.html' %}
{% load static %}

{% block title %}
    La Taverna de Lopen
{% endblock title %}



{% block body %}

<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">

            <form method="GET" action="">
                <input type="text" name="q" placeholder="Buscar jugador" value="{{ request.GET.q }}">
                <button type="submit">Buscar</button>
            </form>

            <a   href="{% url 'tables:players_list'%}">
                <button type="button">X</button>
            </a>

            {% if players %}
                {% for player in players %}
    
                <div class="post-preview">
                    <a href= "{% url 'tables:player_detail' player.id %}">
                    <h3>{{player.name}}  {{player.lastname}} - {{player.age}}</h3>
                    </a>
                    <div style = "display: flex; column-gap: 5 px">
                    <button>
                        <a href="{% url 'tables:player_update' player.id %}" > Editar </a>
                    </button>
                    <button>
                        <a href="{% url 'tables:player_delete' player.id %}" > Borrar </a>
                    </button>

                    </div>


                    
                    <hr class="my-4" />
                </div>

                {% endfor %}
                
            {% else %}
                
                <p>  No hay coincidencias con tu busqueda </p>

            {% endif %}


            
            <a   href="{% url 'tables:player_create' %}">
                <button type="button">Nuevo Jugador</button>
            </a>
            
        </div>
    </div>
</div>

{% endblock body %}

tables/templates/tables/table_create.html
{% extends 'landing_news/father.html' %}
{% load static %}

{% block title %}
    Crea Mesa
{% endblock title %}



{% block body %}

   

    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">

                <h1>Crear Mesa</h1>

                <form action = "{% url 'tables:table_create' %}" method= "post" enctype="multipart/form-data"> {% csrf_token %}
                    {{form.as_p}}

                    <button type= "submit"> Crear </button>

                </form>

                <a   href="{% url 'tables:tables_list'%}">
                    <button type="button">Volver</button>
                </a>
                
            </div>
        </div>
    </div>

{% endblock body %}

tables/templates/tables/table_delete.html
{% extends 'landing_news/father.html' %}
{% load static %}

{% block title %}
    Eliminar Mesa
{% endblock title %}



{% block body %}

   

    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">

                <h1>Eliminar Mesa </h1>

                <form action = "{% url 'tables:table_delete' table.id %}" method= "post" enctype="multipart/form-data"> {% csrf_token %}
                    <p> Esta seguro que desea eliminar la mesa {{table.name}} </p>

                    <button type = "submit"> Confirmar </button>
                    <button ><a href= "{% url 'tables:tables_list'%}"> Cancelar </a></button>

                </form>


                
            </div>
        </div>
    </div>

{% endblock body %}

tables/templates/tables/table_detail.html
{% extends 'landing_news/father.html' %}
{% load static %}

{% block title %}
    Mesa
{% endblock title %}



{% block body %}

    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">

                <h1>{{table.name}}</h1>

                <ul>
                    <li>Juego: {{table.game}}</li>
                    <li>Fecha: {{table.date}}</li>
                    <li>Cantidad maxima de jugadores: {{table.max_players}}</li>
                    <li>Lugares libres: {{table.free_places}} </li>

                </ul>
                <p> {{table.description}} </p>
               
                <a   href="{% url 'tables:tables_list'%}">
                    <button type="button">Volver</button>
                </a>

            </div>
        </div>
    </div>
{% endblock body %}

tables/templates/tables/table_update.html
{% extends 'landing_news/father.html' %}
{% load static %}

{% block title %}
    Editar Mesa
{% endblock title %}



{% block body %}

   

    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">

                <h1>Editar Mesa </h1>

                <form action = "{% url 'tables:table_update' table.id %}" method= "post"> {% csrf_token %}
                    {{form.as_p}}

                    <button type= "submit"> Guardar </button>

                </form>

                <a   href="{% url 'tables:tables_list'%}">
                    <button type="button">Volver</button>
                </a>
                
            </div>
        </div>
    </div>

{% endblock body %}

tables/templates/tables/tables_list.html
{% extends 'landing_news/father.html' %}
{% load static %}

{% block title %}
    La Taverna de Lopen
{% endblock title %}



{% block body %}

<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            

            <form method="GET" action="">
                <input type="text" name="q" placeholder="Buscar mesa" value="{{ request.GET.q }}">
                <button type="submit">Buscar</button>

            </form>

            <a   href="{% url 'tables:tables_list'%}">
                <button type="button">X</button>
            </a>

            

            {% if tables %}
                {% for table in tables %}
    
                <div class="post-preview">
                    <a href= "{% url 'tables:table_detail' table.id %}">
                    <h3>{{table.name}}  {{table.date}}</h3>
                    </a>
                    <p>{{table.game}} - Cantidad de lugares libres {{table.free_places}}
                    <div style = "display: flex; column-gap: 5 px">
                    <button>
                        <a href="{% url 'tables:table_update' table.id %}" > Editar </a>
                    </button>
                    <button>
                        <a href="{% url 'tables:table_delete' table.id %}" > Borrar </a>
                    </button>

                    </div>


                    
                    <hr class="my-4" />
                </div>

                {% endfor %}
                
            {% else %}
                
                <p>  No hay coincidencias con tu busqueda </p>

            {% endif %}


            
            <a   href="{% url 'tables:table_create' %}">
                <button type="button">Nueva Mesa</button>
            </a>
            
        </div>
    </div>
</div>

{% endblock body %}