landing_news/urls.py
from django.urls import path
from landing_news.views import News_list , News_detail, News_create, News_update , News_delete , about

app_name = 'landing_news'

urlpatterns = [
    path('', News_list.as_view(), name='landing'),
    path('detail/<pk>', News_detail.as_view(), name='new_detail'),
    path('create/', News_create.as_view(), name='new_create'),
    path('update/<pk>', News_update.as_view(), name='new_update'),
    path('delete/<pk>', News_delete.as_view(), name='new_delete'),
    path('delete/<pk>', News_delete.as_view(), name='new_delete'),
    path('sobre_mi/', about, name='about'),
]

login/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from login.views import login_view, register, edit_user , show_profile 

app_name = 'login'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register, name='register'),
    path('logout/', LogoutView.as_view(next_page="landing_news:landing"), name='logout'),
    path('profile/', show_profile, name='profile'),
    path('edit_profile/', edit_user, name='edit_profile')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_news.urls')),
    path('games/', include('tables.urls')),
    path('login/', include('login.urls'))


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tables/urls.py
from django.urls import path
from tables.views import (
Player_list , Player_detail, Player_create, Player_update , Player_delete,
Tables_list , Table_detail , Table_create , Table_update , Table_delete
)

app_name = 'tables'

urlpatterns = [
    path('players/', Player_list.as_view(), name='players_list'),
    path('player/detail/<pk>', Player_detail.as_view(), name='player_detail'),
    path('player/create/', Player_create.as_view(), name='player_create'),
    path('player/update/<pk>', Player_update.as_view(), name='player_update'),
    path('player/delete/<pk>', Player_delete.as_view(), name='player_delete'),
]


urlpatterns  += [
    path('tables/', Tables_list.as_view(), name='tables_list'),
    path('table/detail/<pk>', Table_detail.as_view(), name='table_detail'),
    path('table/create/', Table_create.as_view(), name='table_create'),
    path('table/update/<pk>', Table_update.as_view(), name='table_update'),
    path('table/delete/<pk>', Table_delete.as_view(), name='table_delete'),
]

landing_news/models.py
from django.db import models

# Create your models here.

class News(models.Model):
    title = models.CharField(max_length=100, verbose_name="Titulo")
    description = models.TextField(verbose_name="Descripcion")
    date = models.DateTimeField(auto_now=True, verbose_name="Última Modificación")
    original_date =  models.DateTimeField(auto_now_add=True, verbose_name="Fecha Creación")
    picture=models.ImageField(upload_to='news_pictures',null=True, blank=True, verbose_name="Imagen")


    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'Noticia'
        verbose_name_plural = 'Noticias'

            

landing_news/views.py
from .models import News
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView
from django.urls import reverse_lazy
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


class News_list(ListView):
    model = News
    template_name = 'landing_news/landing.html'
    context_object_name = 'news'

    def get_queryset(self):
        query = self.request.GET.get('q')
        queryset= News.objects.all()
        if query:
            queryset = News.objects.filter(title__icontains=query)
        return queryset.order_by('-original_date')    
    




class News_detail(LoginRequiredMixin,DetailView):
    model = News
    context_object_name = 'new'


class News_create(LoginRequiredMixin,CreateView):
    model = News
    template_name = 'landing_news/news_create.html'
    fields = ["title" , "description", "picture"]
    success_url =  reverse_lazy("landing_news:landing")


class News_update(LoginRequiredMixin,UpdateView):
    model = News
    template_name = 'landing_news/news_update.html'
    fields = ('__all__')
    success_url =  reverse_lazy("landing_news:landing")
    context_object_name = 'new'

class News_delete(LoginRequiredMixin,DeleteView):
    model = News
    template_name = 'landing_news/news_delete.html'
    context_object_name = 'new'
    success_url =  reverse_lazy("landing_news:landing")


def about(req):
    return render(req, "landing_news/about.html")

landing_news/templates/landing_news/about.html
{% extends 'landing_news/father.html' %}
{% load static %}

{% block title %}
    Sombre mi
{% endblock title %}


{% block body %}

    

    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <h1>Sobre mi</h1>
                <p> 
                    Hola me llamo Federico Heredia, actualemte soy tesorero de una cooperativa.
                    Ahora estoy en camino de ser Backend Developer, es algo pendiente que tengo en la vida, ya que hace muchos
                    tiempo curse 2 años de ingieneria en sistemas en la UTN pero por complicaciones no pude seguir, todo lo que vi me gusto mucho 
                    y en ese entonces aprendi java. Ahora estoy aprendiendo python y me gustaria seguir con base de datos en profundidad.
                </p>
             
                
            </div>
        </div>
    </div>

{% endblock body %}

landing_news/templates/landing_news/father.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %} {% endblock title %}</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        {% include 'landing_news/navbar.html' %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url( {% static 'assets/img/WOK.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Bienvenido a la taverna de Lopen</h1>
                            <span class="subheading">Comparte  tus historias y crea  tus mesas de juego</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        
        {% block body %} {% endblock body %}


        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                       
                        <div class="small text-center text-muted fst-italic">Heredia Federico 2024</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

landing_news/templates/landing_news/landing.html
{% extends 'landing_news/father.html' %}
{% load static %}

{% block title %}
    La Taverna de Lopen
{% endblock title %}



{% block body %}

<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">

            <form method="GET" action="">
                <input type="text" name="q" placeholder="Buscar noticia x titulo" value="{{ request.GET.q }}">
                <button type="submit">Buscar</button>
            </form>

            <a   href="{% url 'landing_news:landing'%}">
                <button type="button">X</button>
            </a>

            {% if news %}
                {% for new in news %}
    
                <div class="post-preview">
                    <a href= "{% url 'landing_news:new_detail' new.id %}">
                    <h3>{{new.title}}</h3>
                    </a>
                    <h6>{{new.original_date}}</h6>

                    <div style = "display: flex; column-gap: 5 px">
                    <button>
                        <a href="{% url 'landing_news:new_update' new.id %}" > Editar </a>
                    </button>
                    <button>
                        <a href="{% url 'landing_news:new_delete' new.id %}" > Borrar </a>
                    </button>

                    </div>


                    
                    <hr class="my-4" />
                </div>

                {% endfor %}
                
            {% else %}
                
                <p>  No hay coincidencias con tu busqueda </p>

            {% endif %}


            
            <a   href="{% url 'landing_news:new_create' %}">
                <button type="button">Nueva noticia</button>
            </a>
            
        </div>
    </div>
</div>

{% endblock body %}

landing_news/templates/landing_news/navbar.html
 <!-- Navigation-->
 <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto py-4 py-lg-0">
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'landing_news:landing'%}">Noticias</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'tables:tables_list'%}">Mesas</a></li>

                
                {% if request.user.is_staff %} 
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'tables:players_list'%}">Usuarios</a></li>
                {% endif %}
                    
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'landing_news:about'%}">Acerca de mi</a></li>
                
                {% if user.is_authenticated %}
                <li class="nav-item">    
                <p class="nav-link px-lg-3 py-3 py-lg-4"> Bienvenido {{user.username}}
                </li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'login:profile'%}">Mi perfil</a></li>
                <li>
                <form class="nav-link px-lg-3 py-3 py-lg-4" method="post" action="{% url 'login:logout' %}"> {% csrf_token %}
                <button class="btn btn-primary" type="submit">Logout</button>
                </form></li>  
                {% else %}
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'login:login'%}">Ingresar</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'login:register'%}">Registrarse</a></li>
                {% endif %}
                    

            </ul>
        </div>
    </div>
</nav>

landing_news/templates/landing_news/news_create.html
{% extends 'landing_news/father.html' %}
{% load static %}

{% block title %}
    Crea Noticia
{% endblock title %}



{% block body %}

  

    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">

                <h1>Crear Noticia</h1>

                <form action = "{% url 'landing_news:new_create' %}" method= "post" enctype="multipart/form-data"> {% csrf_token %}
                    {{form.as_p}}

                    <button type= "submit"> Crear </button>

                </form>

                <a   href="{% url 'landing_news:landing'%}">
                    <button type="button">Volver</button>
                </a>
                
            </div>
        </div>
    </div>

{% endblock body %}

landing_news/templates/landing_news/news_delete.html
{% extends 'landing_news/father.html' %}
{% load static %}

{% block title %}
    Eliminar Noticia
{% endblock title %}



{% block body %}

    

    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <h1>Eliminar Noticia </h1>

                <form action = "{% url 'landing_news:new_delete' new.id %}" method= "post" enctype="multipart/form-data"> {% csrf_token %}
                    <p> Esta seguro que desea eliminal la noticia {{new.title}} </p>

                    <button type = "submit"> Confirmar </button>
                    <button ><a href= "{% url 'landing_news:landing'%}"> Cancelar </a></button>

                </form>


                
            </div>
        </div>
    </div>

{% endblock body %}

landing_news/templates/landing_news/news_detail.html
{% extends 'landing_news/father.html' %}
{% load static %}

{% block title %}
    Noticia
{% endblock title %}



{% block body %}

    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">

                <h1>{{new.title}}</h1>
                
                {% if new.date == new.original_date %}
                    <p>{{new.date}}</p>
                {% else %}
                    <p>{{new.original_date}}</p>
                    <p>{{new.date}} Fecha de edicion</p> 
                {% endif %}
                    
                
                <p>{{new.description}}</p>
                {% if new.picture %}
                <img src="{{ new.picture.url }}" alt="Foto de {{ new.title }}" width="" height="">
                {% endif %}
                
                <a   href="{% url 'landing_news:landing'%}">
                    <button type="button">Volver</button>
                </a>

            </div>
        </div>
    </div>
{% endblock body %}

landing_news/templates/landing_news/news_update.html
{% extends 'landing_news/father.html' %}
{% load static %}

{% block title %}
    Editar Noticia
{% endblock title %}



{% block body %}

    <h1>Editar Noticia </h1>

    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">

                <form action = "{% url 'landing_news:new_update' new.id %}" method= "post" enctype="multipart/form-data"> {% csrf_token %}
                    {{form.as_p}}

                    <button type= "submit"> Guardar </button>

                </form>

                <a   href="{% url 'landing_news:landing'%}">
                    <button type="button">Volver</button>
                </a>
                
            </div>
        </div>
    </div>

{% endblock body %}